<?php
$country = strtoupper($_SERVER['HTTP_CF_IPCOUNTRY'] ?? '');
$map = ['VN'=>'vi','US'=>'en','GB'=>'en','CA'=>'en','AU'=>'en','FR'=>'fr','DE'=>'de','ES'=>'es','ID'=>'id','TH'=>'th','JP'=>'ja','KR'=>'ko','BR'=>'pt','IT'=>'it'];
$lang = $map[$country] ?? 'en';
?>
<!doctype html>
<html lang="<?= htmlspecialchars($lang) ?>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#0b1220">
  <title>TaiNhacMP3 – YouTube Video Cutter | Minh Dev</title>
  <meta name="description" content="Cắt video YouTube bằng link. Chọn thời gian và tạo MP4 hoặc MP3 nhanh chóng với TaiNhacMP3.">
  <meta name="robots" content="index,follow,max-image-preview:large">
  <meta name="author" content="Minh Dev">
  <meta name="keywords" content="cắt video YouTube, cắt YouTube online, YouTube video cutter, YouTube clip cutter, MP4, MP3, TaiNhacMP3">
  <link rel="canonical" href="https://tainhacmp3.online/">
  <meta property="og:type" content="website"><meta property="og:url" content="https://tainhacmp3.online/"><meta property="og:site_name" content="TaiNhacMP3"><meta property="og:title" content="TaiNhacMP3 – YouTube Video Cutter"><meta property="og:description" content="Cắt video YouTube bằng link và tạo MP4 hoặc MP3.">
  <meta name="twitter:card" content="summary"><meta name="twitter:title" content="TaiNhacMP3 – YouTube Video Cutter"><meta name="twitter:description" content="Cắt video YouTube bằng link và tạo MP4 hoặc MP3.">
  <script type="application/ld+json">{"@context":"https://schema.org","@type":"WebApplication","name":"TaiNhacMP3","url":"https://tainhacmp3.online/","applicationCategory":"MultimediaApplication","operatingSystem":"Web","description":"YouTube video cutter for public content.","author":{"@type":"Person","name":"Minh Dev"},"offers":{"@type":"Offer","price":"0","priceCurrency":"USD"}}</script>
  <link rel="stylesheet" href="assets/style.css?v=4"><link rel="stylesheet" href="assets/ytcut-style.css?v=1">
</head>
<body>
<header class="topbar"><div class="container nav"><a class="brand" href="/"><span class="brand-mark">T</span><span>TaiNhacMP3</span></a><nav><a href="#how" data-i18n="navHow">How it works</a><a href="#faq" data-i18n="navFaq">FAQ</a><select id="language" aria-label="Language"><option value="vi">🇻🇳 Tiếng Việt</option><option value="en">🇺🇸 English</option><option value="fr">🇫🇷 Français</option><option value="de">🇩🇪 Deutsch</option><option value="es">🇪🇸 Español</option><option value="id">🇮🇩 Indonesia</option><option value="th">🇹🇭 ไทย</option><option value="ja">🇯🇵 日本語</option><option value="ko">🇰🇷 한국어</option><option value="pt">🇧🇷 Português</option><option value="it">🇮🇹 Italiano</option></select></nav></div></header>
<main>
<section class="hero"><div class="container hero-inner"><div class="badge"><span></span><span data-i18n="badge">YOUTUBE VIDEO CUTTER</span></div><h1><span data-i18n="hero1">Cut YouTube videos</span><br><em data-i18n="hero2">by link.</em></h1><p class="lead" id="lead">Paste a public YouTube link, choose start and end, then cut your clip.</p><form id="infoForm" class="url-form"><div class="url-box"><span class="link-icon">↗</span><input id="url" type="url" autocomplete="off" placeholder="Paste YouTube URL here..." required><button type="submit" id="getBtn">Get video</button></div></form><div class="trust"><span data-static-i18n="trust1">✓ Accurate timeline</span><span data-static-i18n="trust2">✓ No watermark</span><span data-static-i18n="trust3">✓ MP4 & MP3</span><span data-static-i18n="trust4">✓ Mobile friendly</span></div><div id="message" class="message" role="status"></div>
<section id="editor" class="editor hidden"><div class="video-card"><div class="preview"><img id="thumbnail" alt="Video thumbnail"><div class="preview-shade"></div><div class="play-badge">▶</div></div><div class="video-meta"><div><span class="eyebrow" data-i18n="videoFound">VIDEO FOUND</span><h2 id="videoTitle">YouTube video</h2><p id="channel"></p></div><div class="duration-pill" id="durationLabel">00:00</div></div></div><div class="controls"><div class="control-head"><div><span class="eyebrow" data-i18n="selectClip">SELECT CLIP</span><h3 data-i18n="chooseSection">Choose the section</h3></div><span class="limit" data-i18n="maxClip">Maximum 30 minutes</span></div><div class="timeline-wrap"><div class="timeline" id="timeline"><div class="track"></div><div class="selection" id="selection"><button type="button" class="handle left" id="leftHandle" aria-label="Move start"></button><button type="button" class="handle right" id="rightHandle" aria-label="Move end"></button></div></div><div class="timeline-labels"><span id="startTimeline">00:00</span><span id="endTimeline">00:00</span></div></div><div class="time-grid"><label><span data-i18n="start">Start</span><div class="time-input"><input id="start" inputmode="numeric" value="00:00"><div class="nudge"><button type="button" data-target="start" data-delta="-1">−1s</button><button type="button" data-target="start" data-delta="1">+1s</button></div></div></label><label><span data-i18n="end">End</span><div class="time-input"><input id="end" inputmode="numeric" value="00:30"><div class="nudge"><button type="button" data-target="end" data-delta="-1">−1s</button><button type="button" data-target="end" data-delta="1">+1s</button></div></div></label></div><div class="format-row"><div><span class="eyebrow" data-i18n="outputFormat">OUTPUT FORMAT</span><div class="format-options"><label class="format active"><input type="radio" name="format" value="mp4" checked><span>MP4</span><small data-i18n="video">Video</small></label><label class="format"><input type="radio" name="format" value="mp3"><span>MP3</span><small data-i18n="audio">Audio</small></label></div></div><div class="clip-info"><span data-i18n="clipLengthLabel">Clip length</span><strong id="clipLength">00:30</strong></div></div><button id="cutBtn" class="cut-btn" type="button">✂ Cut & download <span>→</span></button><div id="progressBox" class="progress-box hidden"><div class="progress-top"><span id="progressText">Processing your clip…</span><span id="progressStatus">WORKING</span></div><div class="progress-track"><div id="progressBar"></div></div></div><div id="downloadBox" class="download-box hidden"><div class="success-icon">✓</div><div><strong id="downloadTitle">Your clip is ready</strong><span id="downloadMeta"></span></div><a id="downloadBtn" class="download-btn" href="#" target="_blank" rel="noopener">Download</a></div></div></section>
</div></section>
<section id="how" class="section"><div class="container"><div class="section-kicker" data-i18n="howKicker">HOW IT WORKS</div><h2 data-i18n="howTitle">3 simple steps.</h2><div class="steps"><article><b>01</b><h3 data-i18n="step1Title">Paste</h3><p data-i18n="step1Text">Paste a public YouTube link.</p></article><article><b>02</b><h3 data-i18n="step2Title">Select</h3><p data-i18n="step2Text">Choose the start and end time.</p></article><article><b>03</b><h3 data-i18n="step3Title">Cut</h3><p data-i18n="step3Text">Choose MP4 or MP3 and download.</p></article></div></div></section>
<section id="about" class="section about-section"><div class="container"><div class="section-kicker" data-i18n="aboutKicker">ABOUT TAINHACMP3</div><h2 data-i18n="aboutTitle">Built by Minh Dev.</h2><p class="about-copy" data-i18n="aboutText">A simple and fast tool for cutting public YouTube videos.</p><div class="founder-card"><div class="founder-avatar">MD</div><div><strong>Minh Dev</strong><span data-i18n="founderRole">Founder & developer</span></div></div></div></section>
<section id="faq" class="section faq-section"><div class="container"><div class="section-kicker" data-i18n="faqKicker">FAQ</div><h2 data-i18n="faqTitle">Good to know.</h2><div class="faq"><details><summary data-i18n="faq1Q">How long can a clip be?</summary><p data-i18n="faq1A">Up to 30 minutes per clip.</p></details><details><summary data-i18n="faq2Q">Which formats are available?</summary><p data-i18n="faq2A">MP4 and MP3.</p></details><details><summary data-i18n="faq3Q">Do I need to install anything?</summary><p data-i18n="faq3A">No. Processing is done on the server.</p></details><details><summary data-i18n="faq4Q">Can I cut private videos?</summary><p data-i18n="faq4A">No. Use only public content you are authorized to process.</p></details></div></div></section>
</main><footer><div class="container footer-inner"><span>© 2026 TaiNhacMP3 · <span data-i18n="footerFounder">Founded by Minh Dev</span></span><span data-i18n="footerLegal">Use only content you are authorized to download or process.</span></div></footer><script>window.DEFAULT_LANG="<?= htmlspecialchars($lang) ?>";</script><script src="assets/app.js?v=4"></script><script src="assets/site-i18n.js?v=1"></script>
</body></html>
